# FROM postgres:11.6
FROM postgres:13.3

#COPY ./create-multiple-postgresql-databases.sh /docker-entrypoint-initdb.d/01-7lieues-initdb.sh
#COPY ./mvp_customer_si_local_dump_22-06-2020_17_46_33.sql /docker-entrypoint-initdb.d/02-mvp_customer_si_local_dump_22-06-2020_17_46_33.pgdata
#COPY ./keycloak_db_dump_last.sql /docker-entrypoint-initdb.d/03-keycloak_db_dump_last.pgdata


CMD ["postgres"]
